# Generated by Django 3.2.3 on 2021-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto3',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
